export const FETCH_BEERS_PENDING = 'FETCH_BEERS_PENDING';
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS';
export const FETCH_BEERS_ERROR = 'FETCH_BEERS_ERROR';
export const FETCH_MORE_BEERS_SUCCESS = 'FETCH_MORE_BEERS_SUCCESS';
export const FETCH_MORE_BEERS_LOADING = 'FETCH_MORE_BEERS_LOADING';
